/**
 * File Generation API Route
 * Handles server-side file generation (PPT)
 *
 * This keeps pptxgenjs on the server-side only to avoid webpack bundling issues
 * Uses dynamic import to prevent webpack from bundling Node.js modules
 */

import { NextRequest, NextResponse } from 'next/server';

// Force Node.js runtime for this route (pptxgenjs requires Node.js APIs)
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

interface PPTData {
  title: string;
  slides: string;
  theme?: string;
}

const THEME_COLORS: Record<string, { primary: string; secondary: string; accent: string }> = {
  blue: { primary: '0066CC', secondary: '003366', accent: '66B2FF' },
  green: { primary: '00AA44', secondary: '005522', accent: '66DD88' },
  red: { primary: 'CC0033', secondary: '660022', accent: 'FF6688' },
  purple: { primary: '6633CC', secondary: '331166', accent: 'AA88FF' },
  orange: { primary: 'FF6600', secondary: '993300', accent: 'FFAA66' },
};

async function generatePPTBuffer(data: PPTData): Promise<Blob> {
  // Dynamic import to avoid webpack bundling issues with Node.js modules
  const PptxGenJS = (await import('pptxgenjs')).default;
  const pptx = new PptxGenJS();
  const colors = THEME_COLORS[data.theme || 'blue'] || THEME_COLORS.blue;

  // Set presentation properties
  pptx.author = 'IbnuGPT Agent';
  pptx.title = data.title;
  pptx.subject = 'Generated Presentation';
  pptx.company = 'heyibnu.com';

  // Define master slide
  pptx.defineSlideMaster({
    title: 'MASTER_SLIDE',
    background: { color: 'FFFFFF' },
    objects: [
      // Header bar
      { rect: { x: 0, y: 0, w: '100%', h: 0.75, fill: { color: colors.primary } } },
      // Footer
      {
        text: {
          text: 'Generated by IbnuGPT Agent | heyibnu.com',
          options: {
            x: 0,
            y: 5.2,
            w: '100%',
            h: 0.3,
            align: 'center',
            fontSize: 10,
            color: '999999',
          },
        },
      },
    ],
  });

  // Title slide
  const titleSlide = pptx.addSlide({ masterName: 'MASTER_SLIDE' });
  titleSlide.addText(data.title, {
    x: 0.5,
    y: 2,
    w: 9,
    h: 1.5,
    fontSize: 44,
    bold: true,
    color: colors.secondary,
    align: 'center',
  });
  titleSlide.addText('Generated Presentation', {
    x: 0.5,
    y: 3.5,
    w: 9,
    h: 0.5,
    fontSize: 20,
    color: '666666',
    align: 'center',
  });

  // Parse and add content slides
  const slideContents = data.slides.split('---').map(s => s.trim()).filter(Boolean);

  for (const slideContent of slideContents) {
    const lines = slideContent.split('\n').filter(Boolean);
    const slideTitle = lines[0] || 'Slide';
    const bulletPoints = lines.slice(1);

    const slide = pptx.addSlide({ masterName: 'MASTER_SLIDE' });

    // Slide title
    slide.addText(slideTitle, {
      x: 0.5,
      y: 1,
      w: 9,
      h: 0.75,
      fontSize: 32,
      bold: true,
      color: colors.secondary,
    });

    // Bullet points
    if (bulletPoints.length > 0) {
      const bulletText = bulletPoints.map(point => ({
        text: point.replace(/^[-•*]\s*/, ''),
        options: { bullet: true, indentLevel: 0 },
      }));

      slide.addText(bulletText, {
        x: 0.5,
        y: 2,
        w: 9,
        h: 3,
        fontSize: 18,
        color: '333333',
        valign: 'top',
      });
    }
  }

  // Thank you slide
  const endSlide = pptx.addSlide({ masterName: 'MASTER_SLIDE' });
  endSlide.addText('Thank You!', {
    x: 0.5,
    y: 2.5,
    w: 9,
    h: 1,
    fontSize: 44,
    bold: true,
    color: colors.primary,
    align: 'center',
  });

  // Return as blob
  return pptx.write({ outputType: 'blob' }) as Promise<Blob>;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { type, data } = body;

    if (type !== 'ppt') {
      return NextResponse.json(
        { error: 'Only PPT generation is supported on server' },
        { status: 400 }
      );
    }

    if (!data || !data.title || !data.slides) {
      return NextResponse.json(
        { error: 'Missing required PPT data' },
        { status: 400 }
      );
    }

    const blob = await generatePPTBuffer(data as PPTData);
    const buffer = await blob.arrayBuffer();
    const fileName = `${data.title.replace(/[^a-z0-9]/gi, '_')}.pptx`;

    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'Content-Disposition': `attachment; filename="${fileName}"`,
      },
    });
  } catch (error) {
    console.error('PPT generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate PPT' },
      { status: 500 }
    );
  }
}
