/**
 * Client-side File Generators
 * File: lib/ai/file-generators.ts
 *
 * Utilities for generating PDF files in the browser.
 * PPT generation is handled server-side via API route.
 */

// ============================================
// PDF GENERATOR
// ============================================

export interface PDFData {
  title: string;
  content: string;
  author?: string;
}

export async function generatePDF(data: PDFData): Promise<void> {
  // Dynamic import to avoid SSR issues
  const { jsPDF } = await import('jspdf');

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(data.title, margin, 30);

  // Author
  if (data.author) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100);
    doc.text(`By: ${data.author}`, margin, 40);
    doc.setTextColor(0);
  }

  // Separator line
  doc.setDrawColor(200);
  doc.line(margin, 45, pageWidth - margin, 45);

  // Content
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');

  const lines = doc.splitTextToSize(data.content, maxWidth);
  let y = 55;
  const lineHeight = 7;

  for (const line of lines) {
    if (y > 280) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, margin, y);
    y += lineHeight;
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(
      `Generated by IbnuGPT Agent | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      290,
      { align: 'center' }
    );
  }

  // Save
  doc.save(`${data.title.replace(/[^a-z0-9]/gi, '_')}.pdf`);
}

// ============================================
// PPT GENERATOR (via API)
// ============================================

export interface PPTData {
  title: string;
  slides: string;
  theme?: string;
}

export async function generatePPT(data: PPTData): Promise<void> {
  try {
    const response = await fetch('/api/generate-file', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ type: 'ppt', data }),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || 'Failed to generate PPT');
    }

    // Download the file
    const blob = await response.blob();
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.title.replace(/[^a-z0-9]/gi, '_')}.pptx`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  } catch (error) {
    console.error('PPT generation error:', error);
    throw error;
  }
}
