/**
 * Client-side File Generators
 * File: lib/ai/file-generators.ts
 *
 * Utilities for generating PDF and PPT files in the browser.
 */

import { jsPDF } from 'jspdf';

// ============================================
// PDF GENERATOR
// ============================================

export interface PDFData {
  title: string;
  content: string;
  author?: string;
}

export function generatePDF(data: PDFData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(data.title, margin, 30);

  // Author
  if (data.author) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100);
    doc.text(`By: ${data.author}`, margin, 40);
    doc.setTextColor(0);
  }

  // Separator line
  doc.setDrawColor(200);
  doc.line(margin, 45, pageWidth - margin, 45);

  // Content
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');

  const lines = doc.splitTextToSize(data.content, maxWidth);
  let y = 55;
  const lineHeight = 7;

  for (const line of lines) {
    if (y > 280) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, margin, y);
    y += lineHeight;
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(
      `Generated by IbnuGPT Agent | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      290,
      { align: 'center' }
    );
  }

  // Save
  doc.save(`${data.title.replace(/[^a-z0-9]/gi, '_')}.pdf`);
}

// ============================================
// PPT GENERATOR
// ============================================

export interface PPTData {
  title: string;
  slides: string;
  theme?: string;
}

const THEME_COLORS: Record<string, { primary: string; secondary: string; accent: string }> = {
  blue: { primary: '0066CC', secondary: '003366', accent: '66B2FF' },
  green: { primary: '00AA44', secondary: '005522', accent: '66DD88' },
  red: { primary: 'CC0033', secondary: '660022', accent: 'FF6688' },
  purple: { primary: '6633CC', secondary: '331166', accent: 'AA88FF' },
  orange: { primary: 'FF6600', secondary: '993300', accent: 'FFAA66' },
};

export async function generatePPT(data: PPTData): Promise<void> {
  // Skip on server-side / during build
  if (typeof window === 'undefined') {
    console.warn('PPT generation is only available on the client side');
    return;
  }

  // Dynamic import to avoid Node.js module issues at build time
  // @ts-ignore - dynamic import for pptxgenjs
  const PptxGenJS = (await import(/* webpackIgnore: true */ 'pptxgenjs')).default;
  const pptx = new PptxGenJS();
  const colors = THEME_COLORS[data.theme || 'blue'] || THEME_COLORS.blue;

  // Set presentation properties
  pptx.author = 'IbnuGPT Agent';
  pptx.title = data.title;
  pptx.subject = 'Generated Presentation';
  pptx.company = 'heyibnu.com';

  // Define master slide
  pptx.defineSlideMaster({
    title: 'MASTER_SLIDE',
    background: { color: 'FFFFFF' },
    objects: [
      // Header bar
      { rect: { x: 0, y: 0, w: '100%', h: 0.75, fill: { color: colors.primary } } },
      // Footer
      {
        text: {
          text: 'Generated by IbnuGPT Agent | heyibnu.com',
          options: {
            x: 0,
            y: 5.2,
            w: '100%',
            h: 0.3,
            align: 'center',
            fontSize: 10,
            color: '999999',
          },
        },
      },
    ],
  });

  // Title slide
  const titleSlide = pptx.addSlide({ masterName: 'MASTER_SLIDE' });
  titleSlide.addText(data.title, {
    x: 0.5,
    y: 2,
    w: 9,
    h: 1.5,
    fontSize: 44,
    bold: true,
    color: colors.secondary,
    align: 'center',
  });
  titleSlide.addText('Generated Presentation', {
    x: 0.5,
    y: 3.5,
    w: 9,
    h: 0.5,
    fontSize: 20,
    color: '666666',
    align: 'center',
  });

  // Parse and add content slides
  const slideContents = data.slides.split('---').map(s => s.trim()).filter(Boolean);

  for (const slideContent of slideContents) {
    const lines = slideContent.split('\n').filter(Boolean);
    const slideTitle = lines[0] || 'Slide';
    const bulletPoints = lines.slice(1);

    const slide = pptx.addSlide({ masterName: 'MASTER_SLIDE' });

    // Slide title
    slide.addText(slideTitle, {
      x: 0.5,
      y: 1,
      w: 9,
      h: 0.75,
      fontSize: 32,
      bold: true,
      color: colors.secondary,
    });

    // Bullet points
    if (bulletPoints.length > 0) {
      const bulletText = bulletPoints.map(point => ({
        text: point.replace(/^[-•*]\s*/, ''),
        options: { bullet: true, indentLevel: 0 },
      }));

      slide.addText(bulletText, {
        x: 0.5,
        y: 2,
        w: 9,
        h: 3,
        fontSize: 18,
        color: '333333',
        valign: 'top',
      });
    }
  }

  // Thank you slide
  const endSlide = pptx.addSlide({ masterName: 'MASTER_SLIDE' });
  endSlide.addText('Thank You!', {
    x: 0.5,
    y: 2.5,
    w: 9,
    h: 1,
    fontSize: 44,
    bold: true,
    color: colors.primary,
    align: 'center',
  });

  // Save
  await pptx.writeFile({ fileName: `${data.title.replace(/[^a-z0-9]/gi, '_')}.pptx` });
}

// ============================================
// CONVERSATION EXPORT
// ============================================

export interface ConversationMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export interface ConversationExport {
  title?: string;
  messages: ConversationMessage[];
  model?: string;
  exportedAt?: Date;
}

/**
 * Export conversation to Markdown format
 */
export function exportToMarkdown(data: ConversationExport): void {
  const title = data.title || 'Chat Conversation';
  const date = (data.exportedAt || new Date()).toLocaleString();

  let markdown = `# ${title}\n\n`;
  markdown += `**Exported:** ${date}\n`;
  if (data.model) {
    markdown += `**Model:** ${data.model}\n`;
  }
  markdown += `\n---\n\n`;

  for (const msg of data.messages) {
    const roleLabel = msg.role === 'user' ? '**You:**' : msg.role === 'assistant' ? '**AI:**' : '**System:**';
    markdown += `${roleLabel}\n\n${msg.content}\n\n---\n\n`;
  }

  markdown += `\n*Generated by IbnuGPT Agent at heyibnu.com*\n`;

  // Download as .md file
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.replace(/[^a-z0-9]/gi, '_')}_${new Date().toISOString().slice(0, 10)}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export conversation to PDF format
 */
export async function exportToPDF(data: ConversationExport): Promise<void> {
  const { jsPDF } = await import('jspdf');

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  const title = data.title || 'Chat Conversation';
  const date = (data.exportedAt || new Date()).toLocaleString();

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin, 25);

  // Metadata
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(`Exported: ${date}`, margin, 35);
  if (data.model) {
    doc.text(`Model: ${data.model}`, margin, 42);
  }
  doc.setTextColor(0);

  // Separator
  doc.setDrawColor(200);
  doc.line(margin, 48, pageWidth - margin, 48);

  let y = 58;
  const lineHeight = 6;

  for (const msg of data.messages) {
    // Check if we need a new page
    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    // Role label
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(msg.role === 'user' ? 0 : 50, msg.role === 'user' ? 100 : 100, msg.role === 'user' ? 200 : 150);
    const roleLabel = msg.role === 'user' ? 'You:' : msg.role === 'assistant' ? 'AI:' : 'System:';
    doc.text(roleLabel, margin, y);
    y += lineHeight + 2;

    // Content
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0);

    const lines = doc.splitTextToSize(msg.content, maxWidth);
    for (const line of lines) {
      if (y > 280) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += lineHeight;
    }

    y += 8; // Space between messages
  }

  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(
      `Generated by IbnuGPT Agent | heyibnu.com | Page ${i}/${pageCount}`,
      pageWidth / 2,
      290,
      { align: 'center' }
    );
  }

  // Save
  doc.save(`${title.replace(/[^a-z0-9]/gi, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`);
}

/**
 * Export conversation to JSON format (for backup/import)
 */
export function exportToJSON(data: ConversationExport): void {
  const jsonData = {
    ...data,
    exportedAt: (data.exportedAt || new Date()).toISOString(),
    generator: 'IbnuGPT Agent',
    website: 'heyibnu.com'
  };

  const blob = new Blob([JSON.stringify(jsonData, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `conversation_${new Date().toISOString().slice(0, 10)}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
